export const Menuitems = [
    {
        title:'Record',
        url:'/record',
        subMenu:[
            {
                title:'Exercise',
                url:'/record/exercise'
            },
            {
                title:'Diet',
                url:'/record/diet'
            }
        ]
    },
    {
        title:'Report',
        url:'/report'
    },
    {
        title:'To-Do',
        url:'/diary'
    },
    {
        title:'Profile',
        url:'/profile'
    }
]